#define NO_DATA -1
#define MERCURY_TO_HPA_CONVERSION 33.8638866667
#define DEFAULT_PRESSURE_SETTING 29.92 // inches of mercury

#define COMMAND_ZERO_SENSORS 0
#define COMMAND_SET_PRESSURE 1
#define COMMAND_ENABLE_LOGGING 2
#define COMMAND_DISABLE_LOGGING 3
#define COMMAND_START_FLIGHT 4
#define COMMAND_END_FLIGHT 5

#define COMMAND_ERR 0
#define COMMAND_ACK 1
